apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnect
metadata:
  name: jdbc-connector-cluster
  namespace: integration
  annotations:
    eventstreams.ibm.com/use-connector-resources: "true"
spec:
  replicas: 3
  bootstrapServers: esminimal-kafka-bootstrap.integration.svc:9093
  image: quay.io/kskhong/jdbc-connector:latest
  imagePullPolicy: Always
  template:
    pod:
      imagePullSecrets:
        - name: quay-pull-secret
      metadata:
        annotations:
          eventstreams.production.type: CloudPakForIntegrationNonProduction
          productID: 2a79e49111f44ec3acd89608e56138f5
          productName: IBM Event Streams for Non Production
          productVersion: 11.4.0
          productMetric: VIRTUAL_PROCESSOR_CORE
          productChargedContainers: jdbc-connector-cluster-connect
          cloudpakId: c8b82d189e7545f0892db9ef2731b90d
          cloudpakName: IBM Cloud Pak for Integration
          productCloudpakRatio: "2:1"
  config:
    group.id: jdbc-connector-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3
  tls:
    trustedCertificates:
      - secretName: esminimal-cluster-ca-cert
        certificate: ca.crt
  authentication:
    type: tls
    certificateAndKey:
      certificate: user.crt
      key: user.key
      secretName: jdbc-connector